Repository ChristianPerez34/lifeline_crypto_tbot, pull requests merged in 2021-05, with the labels that each got.

#2 Basic telegram bot.
  .vscode/settings.json
  lifeline_crypto_tbot.py
  poetry.lock
  pyproject.toml
Labels: good first issue

#5 Add telegram to group
  lifeline_crypto_tbot.py
Labels: good first issue

#9 Added handler that automatically greets new users
  .vscode/settings.json
  lifeline_crypto_tbot.py
Labels: enhancement, good first issue

#17 Display CrytpoCoin stats in Telegram
  handler/__init__.py
  handler/base.py
  handler/crypto.py
  lifeline_crypto_tbot.py
  poetry.lock
  pyproject.toml
Labels: enhancement, good first issue

#19 Deployment to heroku
  Procfile
  handler/crypto.py
  lifeline_crypto_tbot.py
  pyproject.toml
Labels: enhancement

#40 Added bot command to display trending coins
  handler/base.py
  handler/crypto.py
  lifeline_crypto_tbot.py
Labels: good first issue

#43 Crypto Price Alert
  handler/base.py
  handler/crypto.py
  lifeline_crypto_tbot.py
Labels: enhancement, good first issue

#44 Added bot command to display latest crypto listings.
  handler/base.py
  handler/crypto.py
  lifeline_crypto_tbot.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#46 Connected KuCoin to bot
  .vscode/launch.json
  app/__init__.py
  app/lifeline_crypto_tbot.py
  handler/base.py
  handler/bot/__init__.py
  handler/bot/kucoin_bot.py
  handler/crypto.py
  lifeline_crypto_tbot.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#53 Trying to figure out why errors propagate
  app/lifeline_crypto_tbot.py
  handler/base.py
  handler/error.py
Labels: bug, good first issue

#56 Added command to restart kucoin bot.
  app/lifeline_crypto_tbot.py
  bot/__init__.py
  bot/kucoin_bot.py
  handler/base.py
  handler/crypto.py
Labels: enhancement

#58 Added latest listings for CoinMarketCap
  handler/crypto.py
Labels: enhancement, good first issue

#60 Retrieves Open Futures Positions on KuCoin Bot Restart
  bot/kucoin_bot.py
  handler/crypto.py
  poetry.lock
  pyproject.toml
Labels: good first issue

#64 Bot alerts on position updates for take profit and stop loss
  bot/kucoin_bot.py
  handler/crypto.py
Labels: enhancement, good first issue

#66 Bsc buy bot
  app/__init__.py
  app/lifeline_crypto_tbot.py
  bot/kucoin_bot.py
  config.py
  handlers/__init__.py
  handlers/base.py
  handlers/crypto.py
  handlers/error.py
  handlers/user.py
  models.py
  poetry.lock
  pyproject.toml
Labels: enhancement, good first issue

#70 Crypto Coin Chart functionality
  app/lifeline_crypto_tbot.py
  handlers/base.py
  handlers/crypto.py
  poetry.lock
  pyproject.toml
Labels: enhancement, good first issue

#72 Added command to sell coins on pancakeswap.
  app/lifeline_crypto_tbot.py
  config.py
  handlers/base.py
  handlers/crypto.py
  poetry.lock
  pyproject.toml
Labels: enhancement, good first issue

#76 Updates to coin lookup
  handlers/__init__.py
  handlers/crypto.py
Labels: good first issue

#78 RE-worked sell coins feature
  handlers/base.py
  handlers/crypto.py
Labels: good first issue

#80 Crypto Coin Candlechart Feature
  api/coinpaprika.py
  api/cryptocompare.py
  app/lifeline_crypto_tbot.py
  handlers/base.py
  handlers/crypto.py
  utils.py
Labels: enhancement, good first issue

#86 Added PNL for closed KuCoin futures positions
  bot/kucoin_bot.py
Labels: good first issue

#89 Fixed bug with KuCoin Futures Contracts
  bot/kucoin_bot.py
Labels: bug

#92 Added error message for insufficient balance
  handlers/crypto.py
Labels: good first issue

#95 COIN VS BASECOIN Chart option
  handlers/base.py
  handlers/crypto.py
Labels: enhancement
